/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas4;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author safik
 */
public class random extends javax.swing.JFrame {
    int kesempatan = 10;
    Random angkaRandom = new Random();
    int tebakan = angkaRandom.nextInt(100) + 1; 
    
    /**
     * Creates new form random
     */
    public random() {
        initComponents();
        this.setLocationRelativeTo(null);
        resetGame();
        start();
    }
    
    private void start(){
        ImageIcon icon = new ImageIcon(Tugas4.class.getResource("hello-well.gif").getFile());
        JOptionPane.showMessageDialog(null, "","",JOptionPane.INFORMATION_MESSAGE, icon);
    }
    
    private void resetGame() {
        kesempatan = 10;
        tebakan = angkaRandom.nextInt(100) + 1; 
        btnTebak.setText("Tebak (" + kesempatan + ")");
        btnTebak.setEnabled(true);
        txtTebakan.setText("");
        txtTebakan.setEditable(true);
        txtJawaban.setText(""); 
        txtScore.setText(""); 
        
        System.out.println("Target : "+tebakan);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Game = new javax.swing.JPanel();
        tengah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTebakan = new javax.swing.JTextField();
        txtJawaban = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        btnTebak = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        atas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Score = new javax.swing.JPanel();
        satas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stengah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreList = new java.awt.List();
        reset = new javax.swing.JButton();
        bawah = new javax.swing.JPanel();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        Game.setLayout(new java.awt.BorderLayout());

        tengah.setBackground(new java.awt.Color(122, 178, 211));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tebak Angka 1 - 100");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tebak Angka");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Jawaban");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Score");

        txtJawaban.setEditable(false);

        txtScore.setEditable(false);

        btnTebak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTebak.setText("Tebak (10)");
        btnTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTebakActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tengahLayout = new javax.swing.GroupLayout(tengah);
        tengah.setLayout(tengahLayout);
        tengahLayout.setHorizontalGroup(
            tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tengahLayout.createSequentialGroup()
                .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tengahLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5))
                    .addGroup(tengahLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJawaban)
                            .addComponent(txtScore)
                            .addGroup(tengahLayout.createSequentialGroup()
                                .addComponent(txtTebakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(tengahLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTebak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addGap(20, 20, 20)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        tengahLayout.setVerticalGroup(
            tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tengahLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTebakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(tengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTebak)
                    .addComponent(btnReset))
                .addGap(44, 44, 44))
        );

        Game.add(tengah, java.awt.BorderLayout.CENTER);

        atas.setBackground(new java.awt.Color(74, 98, 138));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\safik\\Downloads\\image-removebg-preview (13) (3).png")); // NOI18N
        atas.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GAME TEBAK ANGKA");
        atas.add(jLabel2);

        Game.add(atas, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(163, 197, 217));
        jPanel4.setPreferredSize(new java.awt.Dimension(412, 46));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 51, 51));
        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel4.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Game.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Game", Game);

        Score.setLayout(new java.awt.BorderLayout());

        satas.setBackground(new java.awt.Color(74, 98, 138));
        satas.setPreferredSize(new java.awt.Dimension(415, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\safik\\Downloads\\image-removebg-preview (13) (3).png")); // NOI18N
        satas.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GAME TEBAK ANGKA");
        satas.add(jLabel4);

        Score.add(satas, java.awt.BorderLayout.PAGE_START);

        stengah.setBackground(new java.awt.Color(122, 178, 211));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(scoreList);

        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 51, 51));
        reset.setText("Hapus Data");
        reset.setToolTipText("");
        reset.setBorderPainted(false);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stengahLayout = new javax.swing.GroupLayout(stengah);
        stengah.setLayout(stengahLayout);
        stengahLayout.setHorizontalGroup(
            stengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stengahLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(stengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        stengahLayout.setVerticalGroup(
            stengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stengahLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reset)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Score.add(stengah, java.awt.BorderLayout.CENTER);

        bawah.setBackground(new java.awt.Color(163, 197, 217));
        bawah.setPreferredSize(new java.awt.Dimension(415, 46));
        bawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Keluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(255, 51, 51));
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        bawah.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Score.add(bawah, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Score", Score);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTebakActionPerformed
        // TODO add your handling code here:
          
           try {
             if(txtTebakan.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Angka Tebakan harus diisi!","warning",JOptionPane.WARNING_MESSAGE);
                return;
            }   
            
            int angkaTebakan = Integer.parseInt(txtTebakan.getText());
            
            
            if (angkaTebakan < 1 || angkaTebakan > 100) {
                JOptionPane.showMessageDialog(this, "TEBAKAN HARUS BERADA DI ANTARA 1 DAN 100");
                return; 
            }

            if (tebakan > angkaTebakan) {
                kesempatan--;
                txtJawaban.setText("Angka Tebakan Lebih Besar");
            } else if (tebakan < angkaTebakan) {
                kesempatan--;
                txtJawaban.setText("Angka Tebakan Lebih Kecil");
            } else {
                int hasil = kesempatan * 10;
                txtJawaban.setText("Selamat! anda benar : " + tebakan);
                txtScore.setText(String.valueOf(hasil));
                
                ImageIcon icon = new ImageIcon(Tugas4.class.getResource("14.gif").getFile());
                JOptionPane.showMessageDialog(this, "SELAMAT TEBAKAN ANDA BENAR","Congrats",JOptionPane.INFORMATION_MESSAGE, icon);

                String nama = JOptionPane.showInputDialog(this, "SILAKAN MASUKAN NAMA");

                while (nama == null || nama.isEmpty()){
                 JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong","Kesalahan",JOptionPane.WARNING_MESSAGE);
                 nama = JOptionPane.showInputDialog(this, "SILAKAN MASUKAN NAMA");
                } 
                
                scoreList.add("Nama : "+nama + " - "+" Score: "+ hasil); 
                scoreList.repaint(); 
                
                txtTebakan.setEditable(false);
                btnTebak.setEnabled(false);
              
                tebakan = angkaRandom.nextInt(100) + 1; 
            }

            btnTebak.setText("Tebak (" + kesempatan + ")");
            
            if (kesempatan == 0) {
                ImageIcon img = new ImageIcon(Tugas4.class.getResource("gibran.gif").getFile());
                JOptionPane.showMessageDialog(this, "","", 
                        JOptionPane.INFORMATION_MESSAGE, img);
                        
                JOptionPane.showMessageDialog(this, "KESEMPATAN ANDA HABIS!\nAngka yang benar adalah: " + tebakan);
                resetGame();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "TEBAKAN HARUS BERUPA ANGKA");
        }
    }//GEN-LAST:event_btnTebakActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Keluar permainan?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Keluar permainan?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_KeluarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_btnResetActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showConfirmDialog(null,"Ingin Menghapus Data?","Delete",JOptionPane.YES_NO_OPTION);
        if(hapus == JOptionPane.YES_OPTION){
        scoreList.removeAll();
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new random().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Game;
    private javax.swing.JButton Keluar;
    private javax.swing.JPanel Score;
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton reset;
    private javax.swing.JPanel satas;
    private java.awt.List scoreList;
    private javax.swing.JPanel stengah;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtTebakan;
    // End of variables declaration//GEN-END:variables
}
